# api的url,也就是部署go-cqhttp的url
apiHost: http://127.0.0.1:5700
# qq机器人的qq号
selfId: '3056159050'
# 设置管理员
adminUser:
  - '1228014966'
  - '2452973892'
# 监听的qq群
listenGroup:
  - '758796599'
  - '1103372786'
# 正向鉴权,即向go-cqhttp客户端发送消息时进行鉴权
forwardAuthentication:
  enable: true # true\false
  token: 'lmtss'
# 反向鉴权,即接收go-cqhttp客户端消息时进行鉴权
reverseAuthentication:
  enable: true # true\false
  secret: 'sditr'